language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t catarinafranco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true catarinafranco/react-test npm run test

after_success:
  - docker build -t catarinafranco/multi-client ./client
  - docker build -t catarinafranco/multi-nginx ./nginx
  - docker build -t catarinafranco/multi-server ./server
  - docker build -t catarinafranco/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push catarinafranco/multi-client
  - docker push catarinafranco/multi-nginx
  - docker push catarinafranco/multi-server
  - docker push catarinafranco/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-932635764117"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"